apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: viewer
rules:
- apiGroups: ["*"]
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["deployments", "pods", "configmaps", "services", "secrets"]
  verbs: ["get", "watch", "list"]

